<a href="https://colab.research.google.com/github/Janhavi4230/Special-Task/blob/main/SpecialTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Chocolate_Sales.csv to Chocolate_Sales.csv

In [ ]:
filepath='/content/Chocolate_Sales.csv'
df=pd.read_csv(filepath)

In [ ]:
df.head()

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
0,ORD-069833,Truffle Gift Box,Australia,Retail,Arjun Mehta,2022-12-11,3.5,13.72,202.03,71,912.31
1,ORD-090726,85% Dark Bar,Australia,Retail,Arjun Mehta,2023-03-14,9.4,3.30,55.18,84,245.91
2,ORD-042159,70% Dark Bar,Japan,Retail,Hannah Müller,2023-12-21,4.9,18.21,60.65,35,583.7
3,ORD-197166,Hazelnut Milk Bar,Germany,Retail,Arjun Mehta,2023-12-18,15.0,2.66,52.00,92,211.27
4,ORD-112162,Almond Crunch Bar,Australia,Retail,Yuki Sato,2023-08-18,4.4,2.75,187.44,214,549.69

In [ ]:
df.tail()

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
199995,ORD-053460,70% Dark Bar,Australia,Retail,Beatriz Souza,2022-05-27,10.6,3.39,186.19,125,418.56
199996,ORD-010743,Truffle Gift Box,India,Wholesale,Arjun Mehta,2022-09-06,17.3,3.07,42.28,148,366.47
199997,ORD-049690,Salted Caramel Bar,Japan,Online,Arjun Mehta,2022-06-16,18.3,2.74,100.19,149,329.79
199998,ORD-189637,85% Dark Bar,Japan,Wholesale,Rohan Patel,2022-10-14,9.3,14.30,29.96,24,304.51
199999,ORD-061616,Mint Dark Bar,Australia,Retail,Hannah Müller,2022-01-25,7.2,3.01,270.86,131,366.91

In [ ]:
df.shape

(200000, 11)

In [ ]:
df.columns

Index(['Order_ID', 'Product', 'Country', 'Channel', 'Salesperson',
       'Order_Date', 'Discount_Pct', 'Price_per_Box', 'Marketing_Spend',
       'Boxes_Shipped', 'Amount'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Order_ID         200000 non-null  object
 1   Product          200000 non-null  object
 2   Country          200000 non-null  object
 3   Channel          200000 non-null  object
 4   Salesperson      200000 non-null  object
 5   Order_Date       199563 non-null  object
 6   Discount_Pct     199511 non-null  float64
 7   Price_per_Box    199543 non-null  float64
 8   Marketing_Spend  199539 non-null  float64
 9   Boxes_Shipped    200000 non-null  int64
 10  Amount           200000 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 16.8+ MB

In [ ]:
df.describe()

        Discount_Pct  Price_per_Box  Marketing_Spend  Boxes_Shipped
count  199511.000000  199543.000000    199539.000000  200000.000000
mean       13.107457       5.911507        95.450141     139.584105
std         6.374477       4.954976        66.243760     118.665393
min         0.000000       2.040000         4.300000   -1642.000000
25%         8.300000       2.950000        52.270000      67.000000
50%        12.600000       3.280000        78.850000     113.000000
75%        17.500000       4.570000       118.710000     180.000000
max        38.300000      21.650000       798.222443    3811.000000

In [ ]:
df.dtypes

Order_ID            object
Product             object
Country             object
Channel             object
Salesperson         object
Order_Date          object
Discount_Pct       float64
Price_per_Box      float64
Marketing_Spend    float64
Boxes_Shipped        int64
Amount              object
dtype: object

In [ ]:
df.isnull()

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
199995,False,False,False,False,False,False,False,False,False,False,False
199996,False,False,False,False,False,False,False,False,False,False,False
199997,False,False,False,False,False,False,False,False,False,False,False
199998,False,False,False,False,False,False,False,False,False,False,False
199999,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.sum

<bound method DataFrame.sum of           Order_ID             Product    Country    Channel    Salesperson  \
0       ORD-069833    Truffle Gift Box  Australia     Retail    Arjun Mehta
1       ORD-090726        85% Dark Bar  Australia     Retail    Arjun Mehta
2       ORD-042159        70% Dark Bar      Japan     Retail  Hannah Müller
3       ORD-197166   Hazelnut Milk Bar    Germany     Retail    Arjun Mehta
4       ORD-112162   Almond Crunch Bar  Australia     Retail      Yuki Sato
...            ...                 ...        ...        ...            ...
199995  ORD-053460        70% Dark Bar  Australia     Retail  Beatriz Souza
199996  ORD-010743    Truffle Gift Box      India  Wholesale    Arjun Mehta
199997  ORD-049690  Salted Caramel Bar      Japan     Online    Arjun Mehta
199998  ORD-189637        85% Dark Bar      Japan  Wholesale    Rohan Patel
199999  ORD-061616       Mint Dark Bar  Australia     Retail  Hannah Müller

        Order_Date  Discount_Pct  Price_per_Box  Marketing_Spend  \
0       2022-12-11           3.5          13.72           202.03
1       2023-03-14           9.4           3.30            55.18
2       2023-12-21           4.9          18.21            60.65
3       2023-12-18          15.0           2.66            52.00
4       2023-08-18           4.4           2.75           187.44
...            ...           ...            ...              ...
199995  2022-05-27          10.6           3.39           186.19
199996  2022-09-06          17.3           3.07            42.28
199997  2022-06-16          18.3           2.74           100.19
199998  2022-10-14           9.3          14.30            29.96
199999  2022-01-25           7.2           3.01           270.86

        Boxes_Shipped  Amount
0                  71  912.31
1                  84  245.91
2                  35   583.7
3                  92  211.27
4                 214  549.69
...               ...     ...
199995            125  418.56
199996            148  366.47
199997            149  329.79
199998             24  304.51
199999            131  366.91

[200000 rows x 11 columns]>

In [ ]:
df.nunique()

Order_ID           200000
Product                12
Country                 5
Channel                 3
Salesperson            25
Order_Date           2000
Discount_Pct         2517
Price_per_Box        1381
Marketing_Spend     27319
Boxes_Shipped        1521
Amount              85605
dtype: int64

In [ ]:
df.sample(5)

,Order_ID,Product,Country,Channel,Salesperson,Order_Date,Discount_Pct,Price_per_Box,Marketing_Spend,Boxes_Shipped,Amount
64636,ORD-022238,70% Dark Bar,Australia,Retail,Arjun Mehta,2022-06-07,12.1,3.07,74.16,98,267.56
80172,ORD-065049,70% Dark Bar,Australia,Retail,Arjun Mehta,2022-12-03,8.3,4.53,NaN,89,369.51
68325,ORD-047811,Milk Classic Bar,Brazil,Retail,Isabella Rossi,2023-11-02,6.9,2.69,57.07,125,303.39
32979,ORD-044205,Almond Crunch Bar,Brazil,Retail,Arjun Mehta,2022-12-12,8.9,2.95,80.37,309,771.02
69442,ORD-055731,Mixed Assortment Box,Brazil,Wholesale,Arjun Mehta,2023-03-04,6.6,3.10,78.25,380,1103.05

In [20]:
df.min

<bound method DataFrame.min of           Order_ID             Product    Country    Channel    Salesperson  \
0       ORD-069833    Truffle Gift Box  Australia     Retail    Arjun Mehta
1       ORD-090726        85% Dark Bar  Australia     Retail    Arjun Mehta
2       ORD-042159        70% Dark Bar      Japan     Retail  Hannah Müller
3       ORD-197166   Hazelnut Milk Bar    Germany     Retail    Arjun Mehta
4       ORD-112162   Almond Crunch Bar  Australia     Retail      Yuki Sato
...            ...                 ...        ...        ...            ...
199995  ORD-053460        70% Dark Bar  Australia     Retail  Beatriz Souza
199996  ORD-010743    Truffle Gift Box      India  Wholesale    Arjun Mehta
199997  ORD-049690  Salted Caramel Bar      Japan     Online    Arjun Mehta
199998  ORD-189637        85% Dark Bar      Japan  Wholesale    Rohan Patel
199999  ORD-061616       Mint Dark Bar  Australia     Retail  Hannah Müller

        Order_Date  Discount_Pct  Price_per_Box  Marketing_Spend  \
0       2022-12-11           3.5          13.72           202.03
1       2023-03-14           9.4           3.30            55.18
2       2023-12-21           4.9          18.21            60.65
3       2023-12-18          15.0           2.66            52.00
4       2023-08-18           4.4           2.75           187.44
...            ...           ...            ...              ...
199995  2022-05-27          10.6           3.39           186.19
199996  2022-09-06          17.3           3.07            42.28
199997  2022-06-16          18.3           2.74           100.19
199998  2022-10-14           9.3          14.30            29.96
199999  2022-01-25           7.2           3.01           270.86

        Boxes_Shipped  Amount
0                  71  912.31
1                  84  245.91
2                  35   583.7
3                  92  211.27
4                 214  549.69
...               ...     ...
199995            125  418.56
199996            148  366.47
199997            149  329.79
199998             24  304.51
199999            131  366.91

[200000 rows x 11 columns]>

In [ ]:
df.value_counts()

Order_ID    Product               Country    Channel    Salesperson      Order_Date  Discount_Pct  Price_per_Box  Marketing_Spend  Boxes_Shipped  Amount
ORD-200000  70% Dark Bar          Australia  Retail     Arjun Mehta      2022-12-24  19.80         3.32           49.53             100           261.56     1
ORD-000001  White Choco Bar       Brazil     Wholesale  Sora Watanabe    2023-12-17  6.80          13.16          76.03             99            1235.23    1
ORD-000002  Mixed Assortment Box  Germany    Wholesale  Yuki Sato        2022-03-02  1.70          2.82           43.14             190           523.46     1
ORD-000003  Milk Classic Bar      Australia  Retail     Rafael Oliveira  2023-05-11  3.40          2.37           53.83             80            170.85     1
ORD-000004  Pralines Gift Box     Australia  Retail     Priya Sharma     2023-05-05  7.30          3.37           127.85            92            300.95     1
                                                                                                                                                            ..
ORD-000018  Pralines Gift Box     Australia  Retail     Rohan Patel      2023-09-17  24.60         2.48           83.39             130           219.82     1
ORD-000017  Truffle Gift Box      Australia  Retail     Camila Santos    2023-07-15  3.25          15.34          61.65            -36            505.86     1
ORD-000016  Mint Dark Bar         Australia  Retail     Rafael Oliveira  2023-05-15  8.00          2.88           33.47             37            98.47      1
ORD-000015  70% Dark Bar          Australia  Wholesale  Priya Sharma     2022-09-22  16.00         2.87           85.60             151           360.38     1
ORD-000014  70% Dark Bar          Brazil     Retail     Rafael Oliveira  2023-12-26  5.50          3.87           94.13             208           791.46     1
Name: count, Length: 198397, dtype: int64

In [22]:
df.max

<bound method DataFrame.max of           Order_ID             Product    Country    Channel    Salesperson  \
0       ORD-069833    Truffle Gift Box  Australia     Retail    Arjun Mehta
1       ORD-090726        85% Dark Bar  Australia     Retail    Arjun Mehta
2       ORD-042159        70% Dark Bar      Japan     Retail  Hannah Müller
3       ORD-197166   Hazelnut Milk Bar    Germany     Retail    Arjun Mehta
4       ORD-112162   Almond Crunch Bar  Australia     Retail      Yuki Sato
...            ...                 ...        ...        ...            ...
199995  ORD-053460        70% Dark Bar  Australia     Retail  Beatriz Souza
199996  ORD-010743    Truffle Gift Box      India  Wholesale    Arjun Mehta
199997  ORD-049690  Salted Caramel Bar      Japan     Online    Arjun Mehta
199998  ORD-189637        85% Dark Bar      Japan  Wholesale    Rohan Patel
199999  ORD-061616       Mint Dark Bar  Australia     Retail  Hannah Müller

        Order_Date  Discount_Pct  Price_per_Box  Marketing_Spend  \
0       2022-12-11           3.5          13.72           202.03
1       2023-03-14           9.4           3.30            55.18
2       2023-12-21           4.9          18.21            60.65
3       2023-12-18          15.0           2.66            52.00
4       2023-08-18           4.4           2.75           187.44
...            ...           ...            ...              ...
199995  2022-05-27          10.6           3.39           186.19
199996  2022-09-06          17.3           3.07            42.28
199997  2022-06-16          18.3           2.74           100.19
199998  2022-10-14           9.3          14.30            29.96
199999  2022-01-25           7.2           3.01           270.86

        Boxes_Shipped  Amount
0                  71  912.31
1                  84  245.91
2                  35   583.7
3                  92  211.27
4                 214  549.69
...               ...     ...
199995            125  418.56
199996            148  366.47
199997            149  329.79
199998             24  304.51
199999            131  366.91

[200000 rows x 11 columns]>

In [23]:
df.mean

<bound method DataFrame.mean of           Order_ID             Product    Country    Channel    Salesperson  \
0       ORD-069833    Truffle Gift Box  Australia     Retail    Arjun Mehta
1       ORD-090726        85% Dark Bar  Australia     Retail    Arjun Mehta
2       ORD-042159        70% Dark Bar      Japan     Retail  Hannah Müller
3       ORD-197166   Hazelnut Milk Bar    Germany     Retail    Arjun Mehta
4       ORD-112162   Almond Crunch Bar  Australia     Retail      Yuki Sato
...            ...                 ...        ...        ...            ...
199995  ORD-053460        70% Dark Bar  Australia     Retail  Beatriz Souza
199996  ORD-010743    Truffle Gift Box      India  Wholesale    Arjun Mehta
199997  ORD-049690  Salted Caramel Bar      Japan     Online    Arjun Mehta
199998  ORD-189637        85% Dark Bar      Japan  Wholesale    Rohan Patel
199999  ORD-061616       Mint Dark Bar  Australia     Retail  Hannah Müller

        Order_Date  Discount_Pct  Price_per_Box  Marketing_Spend  \
0       2022-12-11           3.5          13.72           202.03
1       2023-03-14           9.4           3.30            55.18
2       2023-12-21           4.9          18.21            60.65
3       2023-12-18          15.0           2.66            52.00
4       2023-08-18           4.4           2.75           187.44
...            ...           ...            ...              ...
199995  2022-05-27          10.6           3.39           186.19
199996  2022-09-06          17.3           3.07            42.28
199997  2022-06-16          18.3           2.74           100.19
199998  2022-10-14           9.3          14.30            29.96
199999  2022-01-25           7.2           3.01           270.86

        Boxes_Shipped  Amount
0                  71  912.31
1                  84  245.91
2                  35   583.7
3                  92  211.27
4                 214  549.69
...               ...     ...
199995            125  418.56
199996            148  366.47
199997            149  329.79
199998             24  304.51
199999            131  366.91

[200000 rows x 11 columns]>